### ISSUE TITLE
Quota information should be updated regularly

### ISSUE THREAD

**Issue by meichenberger** [stepping-stone/sepiola#46] opened 2016-07-22 08:00 UTC
The quota information on the overview screen should be updated regularly. Polling rate should be every 10 minutes as this corresponds with the cronjob on the backup server:

```
# Write quota values every 10 minutes
*/10 * * * * /usr/libexec/backup-utils/checkBackups.pl --quota | logger -t checkBackups.pl
```

**Comment by dev-zero** [comment] 2016-11-26 18:53
This is actually a duplicate of issue #31

**Closed by dev-zero** 2016-11-26 18:53 UTC
Labels: component:core, enhancement
